plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.13'
}

group 'com.stickmangame'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    // Explicitly set to Java 21
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

javafx {
    version = "21.0.1"
    modules = [ 'javafx.controls' ] 
}

application {
    mainClass = 'com.stickmangame.Main'
}